### ISSUE TITLE
blackscreen 

### ISSUE THREAD

**Issue by FutureFlora** [DeinAlbtraumTV/DnD-Client#6]
![Screenshot_3](https://github.com/DeinAlbtraumTV/DnD-Client/assets/155023762/ff3327db-1102-4335-991c-de2532b6f94d)

Black screen, no icons for options

Where coding skill?

Kindly request help.

**Comment by DeinAlbtraumTV** [comment]
should be fixed with version 1.0.10
 https://github.com/DeinAlbtraumTV/DnD-Client/tree/v1.0.10

**Comment by DeinAlbtraumTV** [comment]
Fixed, closing
